#!/bin/bash

setxkbmap -option "caps:swapescape"
xrandr --output DisplayPort-0 --mode 1366x768
xrandr --output HDMI-A-0 --mode 1600x900

xrandr --output DisplayPort-0 --right-of HDMI-A-0

feh --randomize --bg-fill ~/Imagens/Wallpaper/
flameshot
xsetwacom --set "10" MapToOutput HDMI-A-0
xsetwacom --set "15" MapToOutput HDMI-A-0
