#!/bin/bash

show_help() {
    echo "Usage: $0 [OPTIONS]"
    echo "Options:"
    echo "  -h | -help                Show this help message"
    echo "  -k | -key <new-key>       Saves a new key in the script"
    exit 1
}

if ! command -v xclip &> /dev/null
then
    echo "xclip could not be found, please install it to use this script."
    exit 1
fi

KEY=""
FILE_NAME=$0

while [[ "$#" -gt 0 ]]; do
  case $1 in
    -h|--help)
      show_help
      exit 0
      ;;
    -k|--key)
      if [[ -n "$2" ]]; then
        KEY=$2
        sudo sed -i "s/KEY=\"[^\"]*\"/KEY=\"$2\"/" "$FILE_NAME"
        shift
      else
        echo "Error: --key requires a non-empty option argument."
        show_help
        exit 1
      fi
      ;;
    *)
      echo "Error: "$1" is not an valid argument"
      show_help
      exit 1
      ;;
  esac
  shift
done

if [ -z "$KEY" ]; then
    read -sp "Please enter your key: " KEY
    sudo sed -i "s/KEY=\"[^\"]*\"/KEY=\"$KEY\"/" "$FILE_NAME"
    echo
fi

echo "$KEY" | xclip -selection clipboard

echo "Copied."
